# -*- coding: utf-8 -*-
"""content_based.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IbkjOpPHlVE0wXlPdGcWuBDa_RcTtcRP
"""

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def content_based_recommender(user_input, top_n=20):

  # # read data from database
  df_themes = pd.read_pickle("../model_data/themes.pkl")
  df_games = pd.read_pickle("../model_data/games.pkl")
  df_transform = pd.read_pickle("../model_data/category_transform.pkl")

  cols_sum = df_themes.sum(axis=0, numeric_only=True)
  drop_cols = cols_sum[cols_sum <= 20].index
  df_themes.drop(columns=drop_cols, inplace=True)


  # transform the user input into user preference
  def category_transform(user_input):
    columns_list = df_transform.columns.tolist()
    columns_list = columns_list[1:]
    user_preference = np.array([0] * 107)
    for i in range(len(user_input)):
      if user_input[i] == True:
        temp = np.array(df_transform[columns_list[i]].tolist())
        user_preference = user_preference + temp

    return user_preference.tolist()

  # data preprocessing
  df_themes_data = df_themes.iloc[:,1:]
  user_preference = category_transform(user_input)
  avg_ratings = df_games.loc[:,"AvgRating"].to_list()



  # normalize the user preference.
  # If all preferences are false, fallback to average-rating based scores.
  # This avoids divide-by-zero and keeps ranking meaningful.
  pref_sum = float(np.sum(user_preference))
  if pref_sum <= 0:
    sim_scores = avg_ratings
  else:
    normalized_preference = [x / pref_sum for x in user_preference]
    df_normalized = pd.DataFrame([normalized_preference])
    # calculate the similarity scores
    sim_scores = cosine_similarity(df_normalized, df_themes_data).tolist()[0]

  # append average ratings as tie-breaker
  sim_avg = [[sim_scores[i], avg_ratings[i]] for i in range(len(sim_scores))]

  # sorting
  sorted_sim_avg = sorted(enumerate(sim_avg), key=lambda i: i[1], reverse=True)

  return sorted_sim_avg[:top_n]
